# exp setting
ckpt_path: null # checkpoint path, used for evaluation
seed: 42 # random seed
debug: False # debug mode, will use cpu only
devices: [ 0 ] # gpu ids
eval: False

# official evaluation
nuscenes_dataroot: 'data/nuscenes'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool

defaults:
  - method: bevtraj_nusc